#!/usr/bin/env python
# vim: tabstop=8 expandtab shiftwidth=4 softtabstop=4
import cv2, sys, math
import numpy as np

def compare_sq_difference (h1, h2):
    "Work out the correlation between two histograms"
    sumx = sumy = sumxx = sumyy = sumxy = 0.0
    n = len (h1)
    for i in range (0, n):
        v1 = float (h1[i])
        v2 = float (h2[i])
        sumx += v1
        sumy += v2
        sumxx += v1 * v1
        sumxy += v1 * v2
        sumyy += v2 * v2
    v1 = sumxy - sumx * sumy / n
    v2 = math.sqrt((sumxx-sumx*sumx/n) * (sumyy-sumy*sumy/n))
    return abs (v1 / v2)

def compare_correlation (h1, h2):
    "Work out the correlation between two histograms"
    sumx = sumy = sumxx = sumyy = sumxy = 0.0
    n = len (h1)
    for i in range (0, n):
        v1 = float (h1[i])
        v2 = float (h2[i])
        sumx += v1
        sumy += v2
        sumxx += v1 * v1
        sumxy += v1 * v2
        sumyy += v2 * v2
    v1 = sumxy - sumx * sumy / n
    v2 = math.sqrt((sumxx-sumx*sumx/n) * (sumyy-sumy*sumy/n))
    return abs (v1 / v2)

def rgb_histograms (im):
    "Workout one histogram for each color
    in the image"
    r = g = b = []
    return r, g, b

def merge_histograms (r_hist, g_hist, b_hist):
    "Merge all histograms into one large histogram."
    h = []
    return h

#------------------------------------------------------------
# Beginning of program
params = sys.argv
if len(params) < 3:
    print >>sys.stderr, 'Usage:', sys.argv[0], '<probe> <test-images>'
    sys.exit (1)

# Print openCV version info and init
probe_file = params[1]
best_img_val = 0
best_img_file = '?'
do_display = True

# Read probe image and find its histogram.
im = cv2.imread(probe_file)

# Main loop.
# Load image one by one, get their histogram and compare it to the probe image.
for file in params[2:]:
    if file != probe_file:
        print "Processing", file
        im = 

